apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: finanzas-backend-hpa
  labels:
    app: finanzas-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finanzas-backend   # 👈 debe coincidir con el nombre exacto del Deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

