apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: finanzas-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finanzas-backend
  template:
    metadata:
      labels:
        app: finanzas-backend
    spec:
      containers:
        - name: backend
          image: leslym03/finanzas-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-0.mongo-headless:27017/finanzas"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: finanzas-backend
  ports:
    - port: 3001
      targetPort: 3001
  type: NodePort
